### ISSUE TITLE
Outdated URLs in soft binding algorithm list

### ISSUE THREAD

**Issue by crandmck** [c2pa-org/softbinding-algorithm-list#17]
In https://github.com/c2pa-org/softbinding-algorithm-list/blob/main/softbinding-algorithm-list.json, the following URL values for `informationalUrl` do not currently resolve (i.e. return 404):
- For steg.ai: https://github.com/c2pa-org/softbinding-algorithm-list/blob/main/softbinding-algorithm-list.json#L108
- For trufo.ai: https://github.com/c2pa-org/softbinding-algorithm-list/blob/main/softbinding-algorithm-list.json#L122 and https://github.com/c2pa-org/softbinding-algorithm-list/blob/main/softbinding-algorithm-list.json#L136
- For overlai.app: https://github.com/c2pa-org/softbinding-algorithm-list/blob/main/softbinding-algorithm-list.json#L150

For Trufo.ai, perhaps https://github.com/byh-trufo/watermark-benchmark would be appropriate.  I could not find any obvious alternatives for the others.

Reported by @hackerfactor in [CAI Discord](https://discord.com/channels/983153151341371422/1272634885592449056/1283972175937933393).

**Comment by domguinard** [comment]
Thanks @crandmck - we will address that in the WM task force meeting today.

**Comment by domguinard** [comment]
We have corrected a few. We need to get the URLs for Trufo and Overlai.

**Comment by domguinard** [comment]
All URLs are now working, thanks for submitting the issue, closing it now.
